<?php
/**
 * Implementation of hook_shipping_form_alter
 */
function uc_geoloc_form_alter(&$form,$form_state,$form_id){
	if ('uc_cart_checkout_form' == $form_id){
		drupal_add_js(drupal_get_path('module', 'uc_geoloc') .'/autoloc.js');
	}
}
/**
 * Implementation of hook_menu
 */
function uc_geoloc_menu(){
	$items = array();
	$items['geocode'] = array(
		'title' => 'Reverse geocoding',
		'description' => 'Proxy to Google\'s reverse geocoding API',
		'page callback' => 'uc_geoloc_proxy',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);
	return $items;
}
function uc_geoloc_proxy(){
	//header("Content-Type: text/json");
	unset($_GET['q']);
	$q = ''; 
	foreach ($_GET AS $key=>$value) 
	    $q .= $key.'='.$value.'&'; 
	$q = rtrim($q, '&'); 
	
	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, "http://maps.google.com/maps/api/geocode/json?".$q);
	curl_setopt($ch, CURLOPT_HEADER, 0);
	curl_exec($ch);
	curl_close($ch);
	die();
}
